### PR TITLE
Modify baseURL to full path

### PR DESCRIPTION
**Pull request by gewill**
Add compatibility with Perplexity.ai API's distinct endpoint structure.
https://api.perplexity.ai/chat/completions

### CODE REVIEW

**Comment by intitni** [comment]
Thanks for your pull request.

But it will simply break everyone's settings. I would recommend adding a toggle to switch between a base url or a full url, and handle the `openAICompatible` case separately.

**Comment by gewill** [comment]
I also thought about it, but I tried it yesterday and was not familiar enough with the project, so I failed to add toggle with two url. I will try again later.

**Comment by intitni** [comment]
The UI is in `ChatModelEditView.swift`. When you add a field to `ChatModel`, please also mark it with the `FallbackDecoding<EmptyBool>` property wrapper so it's compatible with the old storage.

It will be great if you can also update the `EmbeddingModel`, `EmbeddingModelEditView`, too. But feel free to leave it to me.

**Comment by gewill** [comment]
I add a toggle that switch base URL to full path in `ChatModelEditView` and `EmbeddingModelEditView`.

SCR-20240206-bsze
SCR-20240206-bstf

**Comment by intitni** [comment]
Thank you! It looks great.

But I think the UI is a bit confusing. Do you think we can change the toggle to a segment control and make it look like this?

```
URL [ * Base URL * | Full URL ]                  // when Base URL is selected
    [ Text Field ] /v1/chat/completion           // preview of what will be appended to the URL
                                                 // we may need to add an HStack in BaseURLPicker like APIKeyPicker

URL [ Base URL | * Full URL * ]                  // when full URL is selected
    [ Text Field ]
```

Please let me know if you want to include it in this pull request. Feel free to leave it to me.

**Comment by gewill** [comment]
What's your design is better. Let me do it later.

**Comment by intitni** [comment]
Thank you!

**Comment by gewill** [comment]
My pleasure. Thank you for your kind advice and your open source project.

**Pull request merged**
