### PR TITLE
Added Indexing Changes for Codeium

### PR DESCRIPTION
**Pull request by RoshanNagaram-eng**
- Added Support to extract dir from workspace, before we were just analyzing the workspace and not the actual repos in the workspace for indexing

### CODE REVIEW

**Comment by intitni** [comment]
Thank you!

**Comment by intitni** [comment]
Just some follow up:

It looks like the language server is now able to track multiple workspaces?

If this is the case, and you no longer need multiple language servers for each workspace, you can move the `codeiumServer` from `CodeiumWorkspacePlugin` into `CodeiumExtension`. Make sure to update the `terminate` method, too.

**Comment by RoshanNagaram-eng** [comment]
Just to clarify the language server can track multiple projects within a workspace. Would the suggestion you stated above still apply?

**Comment by intitni** [comment]
Then we should just keep it the way it was.

**Pull request merged**
